// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyBigFilesSelectedIDs(arg1) {
  return window['go']['main']['App']['ApplyBigFilesSelectedIDs'](arg1);
}

export function ApplyJunkSelectedIDs(arg1) {
  return window['go']['main']['App']['ApplyJunkSelectedIDs'](arg1);
}

export function BuildDiskTree(arg1) {
  return window['go']['main']['App']['BuildDiskTree'](arg1);
}

export function CancelOperation() {
  return window['go']['main']['App']['CancelOperation']();
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CleanupLastBigFiles() {
  return window['go']['main']['App']['CleanupLastBigFiles']();
}

export function CleanupLastDuplicates() {
  return window['go']['main']['App']['CleanupLastDuplicates']();
}

export function CleanupLastJunk() {
  return window['go']['main']['App']['CleanupLastJunk']();
}

export function CleanupPaths(arg1, arg2) {
  return window['go']['main']['App']['CleanupPaths'](arg1, arg2);
}

export function DeleteDuplicatePaths(arg1) {
  return window['go']['main']['App']['DeleteDuplicatePaths'](arg1);
}

export function DeleteDuplicates(arg1) {
  return window['go']['main']['App']['DeleteDuplicates'](arg1);
}

export function ExecuteCleanup(arg1) {
  return window['go']['main']['App']['ExecuteCleanup'](arg1);
}

export function ForceCleanup(arg1) {
  return window['go']['main']['App']['ForceCleanup'](arg1);
}

export function FormatBytes(arg1) {
  return window['go']['main']['App']['FormatBytes'](arg1);
}

export function GetAppIconDataURL(arg1) {
  return window['go']['main']['App']['GetAppIconDataURL'](arg1);
}

export function GetAppLeftovers(arg1) {
  return window['go']['main']['App']['GetAppLeftovers'](arg1);
}

export function GetAuditLogPath() {
  return window['go']['main']['App']['GetAuditLogPath']();
}

export function GetBigFilesCategoryRows() {
  return window['go']['main']['App']['GetBigFilesCategoryRows']();
}

export function GetBigFilesDefaults() {
  return window['go']['main']['App']['GetBigFilesDefaults']();
}

export function GetBigFilesSelectionSummary() {
  return window['go']['main']['App']['GetBigFilesSelectionSummary']();
}

export function GetCatalogCategories() {
  return window['go']['main']['App']['GetCatalogCategories']();
}

export function GetDiskSummary() {
  return window['go']['main']['App']['GetDiskSummary']();
}

export function GetJunkCategoryRows() {
  return window['go']['main']['App']['GetJunkCategoryRows']();
}

export function GetJunkSelectionSummary() {
  return window['go']['main']['App']['GetJunkSelectionSummary']();
}

export function GetLastAppsScan() {
  return window['go']['main']['App']['GetLastAppsScan']();
}

export function GetLastBigFilesScan() {
  return window['go']['main']['App']['GetLastBigFilesScan']();
}

export function GetLastDiskMap() {
  return window['go']['main']['App']['GetLastDiskMap']();
}

export function GetLastDuplicates() {
  return window['go']['main']['App']['GetLastDuplicates']();
}

export function GetLastJunkScan() {
  return window['go']['main']['App']['GetLastJunkScan']();
}

export function GetPermissionStatus() {
  return window['go']['main']['App']['GetPermissionStatus']();
}

export function GetRecentAuditLog(arg1) {
  return window['go']['main']['App']['GetRecentAuditLog'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTopFiles(arg1, arg2) {
  return window['go']['main']['App']['GetTopFiles'](arg1, arg2);
}

export function ListApps() {
  return window['go']['main']['App']['ListApps']();
}

export function ListDiskChildren(arg1) {
  return window['go']['main']['App']['ListDiskChildren'](arg1);
}

export function OpenAuditLog() {
  return window['go']['main']['App']['OpenAuditLog']();
}

export function OpenFullDiskAccessSettings() {
  return window['go']['main']['App']['OpenFullDiskAccessSettings']();
}

export function PickFolders(arg1, arg2) {
  return window['go']['main']['App']['PickFolders'](arg1, arg2);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function PreviewCleanup(arg1) {
  return window['go']['main']['App']['PreviewCleanup'](arg1);
}

export function PreviewLastBigFiles() {
  return window['go']['main']['App']['PreviewLastBigFiles']();
}

export function PreviewLastJunk() {
  return window['go']['main']['App']['PreviewLastJunk']();
}

export function PruneDiskPath(arg1) {
  return window['go']['main']['App']['PruneDiskPath'](arg1);
}

export function RefreshPermissions() {
  return window['go']['main']['App']['RefreshPermissions']();
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanAppLeftovers(arg1) {
  return window['go']['main']['App']['ScanAppLeftovers'](arg1);
}

export function ScanApps() {
  return window['go']['main']['App']['ScanApps']();
}

export function ScanBigFiles(arg1) {
  return window['go']['main']['App']['ScanBigFiles'](arg1);
}

export function ScanDuplicates(arg1) {
  return window['go']['main']['App']['ScanDuplicates'](arg1);
}

export function ScanJunk() {
  return window['go']['main']['App']['ScanJunk']();
}

export function SelectArchivesOnly(arg1) {
  return window['go']['main']['App']['SelectArchivesOnly'](arg1);
}

export function SelectBigFilesArchivesOnly() {
  return window['go']['main']['App']['SelectBigFilesArchivesOnly']();
}

export function SelectBigFilesLargeOnly() {
  return window['go']['main']['App']['SelectBigFilesLargeOnly']();
}

export function SelectBigFilesOnly(arg1) {
  return window['go']['main']['App']['SelectBigFilesOnly'](arg1);
}

export function SelectJunkSafeOnly() {
  return window['go']['main']['App']['SelectJunkSafeOnly']();
}

export function SelectSafeOnly(arg1) {
  return window['go']['main']['App']['SelectSafeOnly'](arg1);
}

export function SetBigFilesCategorySelected(arg1, arg2) {
  return window['go']['main']['App']['SetBigFilesCategorySelected'](arg1, arg2);
}

export function SetBigFilesItemSelected(arg1, arg2) {
  return window['go']['main']['App']['SetBigFilesItemSelected'](arg1, arg2);
}

export function SetDuplicateKeepers(arg1) {
  return window['go']['main']['App']['SetDuplicateKeepers'](arg1);
}

export function SetJunkCategorySelected(arg1, arg2) {
  return window['go']['main']['App']['SetJunkCategorySelected'](arg1, arg2);
}

export function SetJunkItemSelected(arg1, arg2) {
  return window['go']['main']['App']['SetJunkItemSelected'](arg1, arg2);
}

export function ToggleCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleCategory'](arg1, arg2, arg3);
}

export function TrashPath(arg1) {
  return window['go']['main']['App']['TrashPath'](arg1);
}

export function UninstallApp(arg1) {
  return window['go']['main']['App']['UninstallApp'](arg1);
}
