// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function BuildDiskTree(arg1:string):Promise<model.DirNode>;

export function CancelOperation():Promise<void>;

export function CancelScan():Promise<void>;

export function DeleteDuplicates(arg1:model.DuplicateDeleteRequest):Promise<void>;

export function ExecuteCleanup(arg1:Array<model.ScanItem>):Promise<model.CleanupReport>;

export function ForceCleanup(arg1:Array<model.ScanItem>):Promise<void>;

export function FormatBytes(arg1:number):Promise<string>;

export function GetAppLeftovers(arg1:string):Promise<model.LeftoverGroup>;

export function GetAuditLogPath():Promise<string>;

export function GetBigFilesDefaults():Promise<model.BigFilesScanRequest>;

export function GetCatalogCategories():Promise<Array<model.CategorySummary>>;

export function GetDiskSummary():Promise<model.DiskSummary>;

export function GetLastAppsScan():Promise<Array<model.InstalledApp>>;

export function GetLastBigFilesScan():Promise<Array<model.ScanItem>>;

export function GetLastDiskMap():Promise<model.DiskMapSnapshot>;

export function GetLastDuplicates():Promise<Array<model.DuplicateGroup>>;

export function GetLastJunkScan():Promise<Array<model.ScanItem>>;

export function GetPermissionStatus():Promise<model.PermissionStatus>;

export function GetSettings():Promise<model.AppSettings>;

export function GetTopFiles(arg1:string,arg2:number):Promise<Array<model.DirNode>>;

export function ListApps():Promise<Array<model.InstalledApp>>;

export function OpenFullDiskAccessSettings():Promise<void>;

export function Ping():Promise<string>;

export function PreviewCleanup(arg1:Array<model.ScanItem>):Promise<model.CleanupReport>;

export function RefreshPermissions():Promise<model.PermissionStatus>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SaveSettings(arg1:model.AppSettings):Promise<void>;

export function ScanAppLeftovers(arg1:string):Promise<model.LeftoverGroup>;

export function ScanApps():Promise<Array<model.InstalledApp>>;

export function ScanBigFiles(arg1:model.BigFilesScanRequest):Promise<Array<model.ScanItem>>;

export function ScanDuplicates(arg1:Array<string>):Promise<Array<model.DuplicateGroup>>;

export function ScanJunk():Promise<Array<model.ScanItem>>;

export function SelectArchivesOnly(arg1:Array<model.ScanItem>):Promise<Array<model.ScanItem>>;

export function SelectBigFilesOnly(arg1:Array<model.ScanItem>):Promise<Array<model.ScanItem>>;

export function SelectSafeOnly(arg1:Array<model.ScanItem>):Promise<Array<model.ScanItem>>;

export function ToggleCategory(arg1:Array<model.ScanItem>,arg2:string,arg3:boolean):Promise<Array<model.ScanItem>>;

export function TrashPath(arg1:string):Promise<model.DeleteResult>;

export function UninstallApp(arg1:model.UninstallSelection):Promise<void>;
